api:
  title: Divisao de contas
  description: Api de divisao de contas
  version: v0.0.1

server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/divisaodecontas?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: OuPfme45oAM6m6S8lqy4PQfxlYFlCnmPzyaloZ5Zw=
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate-ddl: true
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


security:
  keystore:
    resource: "classpath:security/auth.jks"
    type: JKS
    password: changeit
    key:
      alias: jwt-signer
      password: changeit